# Generated by Django 4.2.23 on 2025-08-26 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_initial'),
        ('patient', '0002_billing_prescription_billing_stripe_payment_intent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'date', 'time')},
        ),
    ]
